# Generated by Django 4.2 on 2023-11-07 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_order_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_id',
        ),
    ]
